sudo: required
dist: trusty

os:
  - linux

language: node_js
node_js:
  - "8"
  - "10"
  - "12"

cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm run test-cover

after_script:
  - npm run coveralls

notifications:
  webhooks: https://coveralls.io/webhook?repo_token=COVERALLS_REPO_TOKEN
